src/controllers/blacklist.py
from flask import render_template, redirect, url_for, flash, request
from flask_login import current_user

from models.models import blacklisted_meals, Meal
from models.models import db


def view():
    meals = (db.session.query(Meal)
             .join(blacklisted_meals, Meal.id == blacklisted_meals.c.meal_id)
             .filter(blacklisted_meals.c.user_id == current_user.id)
             .all())
    return render_template('menu/blacklist.html', meals=meals)


def add(meal_id, history_date):
    meal = db.session.query(Meal).get(meal_id)
    if meal:
        new_blacklist = blacklisted_meals.insert().values(meal_id=meal_id, user_id=current_user.id)
        try:
            db.session.execute(new_blacklist)
            db.session.commit()
            flash(f'Meal "{meal.name}" has been added to blacklist! '
                  f'Please regenerate menu for it to exclude "{meal.name}"', 'success')
        except:
            db.session.rollback()
            flash(f'Error! Could not add meal "{meal.name}" to blacklist!', 'danger')

    return redirect(url_for('menu.history', date=history_date))


def remove(meal_id, return_page, history_date):
    stmt = blacklisted_meals.delete().where(
        blacklisted_meals.c.meal_id == meal_id,
        blacklisted_meals.c.user_id == current_user.id
    )
    result = db.session.execute(stmt)
    db.session.commit()

    meal = db.session.query(Meal).get(meal_id)

    if result:
        flash(f'Meal "{meal.name}" has been removed from blacklist! '
              f'Please regenerate menu for it to include "{meal.name}"', 'success')
    else:
        flash(f'Meal "{meal.name}" is not in blacklist!', 'danger')

    if return_page == 'history':
        return redirect(url_for('menu.history', date=history_date))
    elif return_page == 'blacklist':
        return redirect(url_for('blacklist.view'))

src/controllers/history.py
from flask import render_template, redirect, url_for, request
from flask_login import current_user
from datetime import datetime, timedelta

from models.models import db, Meal, user_meal, blacklisted_meals


def history():
    date_str = request.args.get('date')
    if date_str is None:
        date = datetime.today().date()
    else:
        try:
            date = datetime.strptime(date_str, '%Y-%m-%d').date()
        except ValueError:
            today_str = datetime.today().date()
            return redirect(url_for('menu.history', date=today_str))

    user_meal_associations = db.session.query(user_meal).filter_by(user_id=current_user.id, date=date).all()
    meals_data = []
    for association in user_meal_associations:
        meal = Meal.query.get(association.meal_id)
        blacklisted = db.session.query(blacklisted_meals).filter_by(user_id=current_user.id, meal_id=meal.id).first()
        if meal:
            portion_size = association.portion
            meal_data = {
                'meal': meal,
                'date': association.date,
                'portion': round(portion_size * 100, 1),
                'calories': round(meal.calories * portion_size),
                'proteins': round(meal.proteins * portion_size, 1),
                'fats': round(meal.fats * portion_size, 1),
                'carbohydrates': round(meal.carbohydrates * portion_size, 1),
                'price': round(meal.price * portion_size, 2),
                'image': url_for('static', filename='images/' + meal.image_src),
                'blacklisted': blacklisted is not None
            }
            meals_data.append(meal_data)

    total_calories = round(sum(meal['calories'] for meal in meals_data))
    total_proteins = round(sum(meal['proteins'] for meal in meals_data), 1)
    total_fats = round(sum(meal['fats'] for meal in meals_data), 1)
    total_carbohydrates = round(sum(meal['carbohydrates'] for meal in meals_data), 1)
    total_price = round(sum(meal['price'] for meal in meals_data), 2)

    prev_date = date - timedelta(days=1)
    next_date = date + timedelta(days=1)
    today = datetime.today().date()

    return render_template('menu/history.html',
                           today=today,
                           prev_date=prev_date,
                           next_date=next_date,
                           date=date,

                           meals=meals_data,

                           total_calories=total_calories,
                           total_proteins=total_proteins,
                           total_fats=total_fats,
                           total_carbohydrates=total_carbohydrates,
                           total_price=total_price)

src/controllers/menu.py
from flask import render_template, request, redirect, url_for, flash
from pulp import LpProblem, LpMinimize, LpVariable, lpSum, value, PULP_CBC_CMD
from datetime import datetime, timedelta, date as d
from sqlalchemy import insert
from flask_login import current_user

from models.models import Meal, user_meal, db, blacklisted_meals


def create_menu_view():
    user = current_user
    errors = {}

    if request.method == 'POST':
        # validates inputs
        errors = validate_nutrients()
        if errors:
            return render_template('menu/create-menu.html', form_data=request.form, errors=errors)

        # gets inputs
        date = datetime.strptime(request.form['date'], '%Y-%m-%d').date()
        n_days_ago = int(request.form['n_days_ago'])

        min_calories = float(request.form['min_calories'])
        max_calories = float(request.form['max_calories'])
        min_fats = float(request.form['min_fats'])
        max_fats = float(request.form['max_fats'])
        min_proteins = float(request.form['min_proteins'])
        max_proteins = float(request.form['max_proteins'])
        min_carbohydrates = float(request.form['min_carbohydrates'])
        max_carbohydrates = float(request.form['max_carbohydrates'])

        # gets meal ids from last n days
        exclude_meal_ids = get_last_n_days_meal_ids(user.id, date, n_days_ago)

        # gets blacklisted meal ids
        exclude_meal_ids += get_blacklisted_meal_ids(user.id)

        # gets user preferences
        user_preferences = get_user_preferences(user)

        # gets meals
        meals = Meal.query.filter_by(**user_preferences).filter(~Meal.id.in_(exclude_meal_ids)).all()

        # error message if no meals found
        if not meals:
            errors['menu'] = 'No meals found that match your food preferences!'
            return render_template('menu/create-menu.html', form_data=request.form, errors=errors)
        # creates menu
        if meals:
            meals_portions = generate_menu(meals, min_calories, max_calories, min_fats, max_fats, min_proteins,
                                           max_proteins, min_carbohydrates, max_carbohydrates, 5)

            # error message if no optimal menu found
            is_menu_valid = validate_menu(meals_portions, min_calories, max_calories, min_fats, max_fats, min_proteins,
                                          max_proteins, min_carbohydrates, max_carbohydrates, 5)

            if is_menu_valid:
                flash(f'Menu has for {date} been created!', 'success')
                delete_menu(user.id, date)
                save_menu(meals_portions, user.id, date)

                db.session.commit()

                return redirect(url_for('menu.history', date=date))
            else:
                errors['menu'] = 'No optimal menu found that match your preferences. Please change your preferences!'
                return render_template('menu/create-menu.html', form_data=request.form, errors=errors)

    return render_template('menu/create-menu.html', form_data=request.form, errors=errors, today=d.today())


def validate_nutrients():
    errors = {}

    nutrients = ['calories', 'proteins', 'fats', 'carbohydrates']
    for nutrient in nutrients:
        min_nutrient = request.form.get(f'min_{nutrient}')
        max_nutrient = request.form.get(f'max_{nutrient}')

        # min nutrients should be less than max nutrients
        if not min_nutrient or not max_nutrient or float(min_nutrient) >= float(max_nutrient):
            errors[nutrient] = ('Invalid input: ' + nutrient.capitalize() + ' min should be less than ' +
                                nutrient.capitalize() + ' max.')

    return errors


def get_last_n_days_meal_ids(user_id, date, n_days_ago):
    if n_days_ago == 0:
        return []

    date_n_days_ago = date - timedelta(days=n_days_ago)
    meals = db.session.query(user_meal).filter(
        user_meal.c.user_id == user_id,
        user_meal.c.date >= date_n_days_ago,
        user_meal.c.date < date).all()
    if meals:
        return [meal.meal_id for meal in meals]
    else:
        return []


def get_blacklisted_meal_ids(user_id):
    meals = (db.session.query(Meal)
             .join(blacklisted_meals, Meal.id == blacklisted_meals.c.meal_id)
             .filter(blacklisted_meals.c.user_id == user_id)
             .all())
    if meals:
        return [meal.id for meal in meals]
    else:
        return []


def get_user_preferences(user):
    user_preferences = {attr: getattr(user, attr) for attr in
                        ['gluten_free', 'vegan', 'vegetarian', 'dairy_free']}
    for preference, v in list(user_preferences.items()):
        if not v:
            del user_preferences[preference]
    return user_preferences


def delete_menu(user_id, date):
    stmt = user_meal.delete().where(user_meal.c.user_id == user_id, user_meal.c.date == date)
    db.session.execute(stmt)


def save_menu(meals_portions, user_id, date):
    for meal_id, portion in meals_portions.items():
        stmt = insert(user_meal).values(user_id=user_id, meal_id=meal_id, date=date, portion=portion)
        db.session.execute(stmt)


def generate_menu(meals, min_calories, max_calories, min_fats, max_fats, min_proteins, max_proteins, min_carbohydrates,
                  max_carbohydrates, max_meal_size):
    # Define the problem
    prob = LpProblem("OptimalMenu", LpMinimize)

    # Define the decision variables
    meal_vars = LpVariable.dicts("Meals", [meal.id for meal in meals], 0)

    # Define the objective function
    prob += lpSum([meal_vars[meal.id] * meal.price for meal in meals])

    # Define the constraints
    prob += lpSum([meal_vars[meal.id] * getattr(meal, 'calories') for meal in meals]) >= min_calories
    prob += lpSum([meal_vars[meal.id] * getattr(meal, 'calories') for meal in meals]) <= max_calories

    prob += lpSum([meal_vars[meal.id] * getattr(meal, 'fats') for meal in meals]) >= min_fats
    prob += lpSum([meal_vars[meal.id] * getattr(meal, 'fats') for meal in meals]) <= max_fats

    prob += lpSum([meal_vars[meal.id] * getattr(meal, 'proteins') for meal in meals]) >= min_proteins
    prob += lpSum([meal_vars[meal.id] * getattr(meal, 'proteins') for meal in meals]) <= max_proteins

    prob += lpSum([meal_vars[meal.id] * getattr(meal, 'carbohydrates') for meal in meals]) >= min_carbohydrates
    prob += lpSum([meal_vars[meal.id] * getattr(meal, 'carbohydrates') for meal in meals]) <= max_carbohydrates

    prob += lpSum([meal_vars[meal.id] for meal in meals]) <= max_meal_size

    # Solve the problem
    prob.solve(PULP_CBC_CMD(msg=0))

    # print("The total cost of this balanced diet is: ${}".format(round(value(prob.objective), 2)))
    # print("The total calories of this balanced diet is: {}".format(
    #     round(value(lpSum([meal_vars[meal.id] * getattr(meal, 'calories') for meal in meals])), 2)))
    # print("The total fats of this balanced diet is: {}".format(
    #     round(value(lpSum([meal_vars[meal.id] * getattr(meal, 'fats') for meal in meals])), 2)))
    # print("The total proteins of this balanced diet is: {}".format(
    #     round(value(lpSum([meal_vars[meal.id] * getattr(meal, 'proteins') for meal in meals])), 2)))
    # print("The total carbohydrates of this balanced diet is: {}".format(
    #     round(value(lpSum([meal_vars[meal.id] * getattr(meal, 'carbohydrates') for meal in meals])), 2)))

    # Extract and return the solution
    meals_portions = {}
    for v in prob.variables():
        if v.varValue > 0:
            meal_id = int(v.name.split('_')[1])  # Extract the meal ID from the variable name
            meals_portions[meal_id] = v.varValue

    return meals_portions


def validate_menu(meals_portions, min_calories, max_calories, min_fats, max_fats, min_proteins, max_proteins,
                  min_carbohydrates, max_carbohydrates, max_meal_size):
    total_cost = 0
    total_calories = 0
    total_fats = 0
    total_proteins = 0
    total_carbohydrates = 0

    for meal_id, portion in meals_portions.items():
        meal = Meal.query.get(meal_id)
        total_cost += meal.price * portion
        total_calories += meal.calories * portion
        total_fats += meal.fats * portion
        total_proteins += meal.proteins * portion
        total_carbohydrates += meal.carbohydrates * portion

    total_cost = round(total_cost, 2)
    total_calories = round(total_calories)
    total_fats = round(total_fats,1)
    total_proteins = round(total_proteins,1)
    total_carbohydrates = round(total_carbohydrates,1)

    print('>>>>>>> Algorithm Results:')
    print('>>>>>>> Total Cost:', total_cost)
    print('>>>>>>> Total Calories:', total_calories)
    print('>>>>>>> Total Fats:', total_fats)
    print('>>>>>>> Total Proteins:', total_proteins)
    print('>>>>>>> Total Carbohydrates:', total_carbohydrates)

    if len(meals_portions) > max_meal_size:
        return False

    if not (min_calories <= total_calories <= max_calories):
        return False

    if not (min_fats <= total_fats <= max_fats):
        return False

    if not (min_proteins <= total_proteins <= max_proteins):
        return False

    if not (min_carbohydrates <= total_carbohydrates <= max_carbohydrates):
        return False

    return True

src/routes/blacklist.py
from flask import Blueprint
from flask_login import login_required

from controllers.blacklist import view, add, remove

blacklist_blueprint = Blueprint('blacklist', __name__, url_prefix='/blacklist')

blacklist_blueprint.route('/', methods=['GET'])(login_required(view))
blacklist_blueprint.route('/add/<meal_id>/<history_date>', methods=['GET'])(login_required(add))
blacklist_blueprint.route('/remove/<meal_id>/<return_page>/<history_date>', methods=['GET'])(login_required(remove))

src/routes/menu.py
from flask import Blueprint
from flask_login import login_required

from controllers.menu import create_menu_view
from controllers.history import history

menu_blueprint = Blueprint('menu', __name__)

menu_blueprint.route('/create-menu', methods=['GET', 'POST'])(login_required(create_menu_view))
menu_blueprint.route('/history', methods=['GET'])(login_required(history))

src/templates/menu/blacklist.html
{%  extends 'base.html' %}

{% block head %}
    <title>Blacklist</title>
{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="mx-auto text-center p-2">Blacklist</h1>

        {% for meal in meals %}
        <div class="row mb-4">
            <div class="col">
                <div class="card">
                    <div class="row g-0 d-flex align-items-center">
                        <div class="col-lg-3 col-md-5">
                            <img src="{{ url_for('static', filename='images/' + meal.image_src) }}" class="card-img-top" alt="Meal image">
                        </div>
                        <div class="col-lg-7 col-md-5">
                            <div class="card-body">
                                <h5 class="card-title">{{ meal.name }}</h5>
                                <p class="card-text">
                                    Portion: {{ 100 }} g<br>
                                    Price: {{ meal.price }} €<br>
                                    Calories: {{ meal.calories }} kcal<br>
                                    Proteins: {{ meal.proteins }} g<br>
                                    Fats: {{ meal.fats }} g<br>
                                    Carbohydrates: {{ meal.carbohydrates }} g
                                </p>
                            </div>
                        </div>
                        <div class="col-lg-2 col-md-2 text-center">
                             <a class="btn btn-danger m-sm-2" href="{{ url_for('blacklist.remove', meal_id=meal.id, return_page='blacklist', history_date='none') }}" role="button" onclick="return confirm('Are you sure you want to remove this meal from the blacklist?')">Remove from blacklist</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
{% endblock %}

src/templates/menu/create-menu.html
{%  extends 'base.html' %}

{% block head %}
    <title>Create menu</title>
{% endblock %}

{% block body %}
    <div class="container">
        <div class="col-lg-6 offset-lg-3">
            <h1 class="mx-auto text-center p-2">Create menu</h1>

            <form method="post">
                <div class="form-group mb-3">
                    <label for="date">Date:</label>
                    <input id="date" name="date" class="form-control" type="date" value="{{ form_data.date if form_data and form_data.date else today }}" required/>
                </div>

                <div class="form-group mb-3">
                    <label for="n_days_ago">Exclude meals from last n days</label>
                    <select class="form-select" id="n_days_ago" name="n_days_ago" required>
                        <option value="0" {{ "" if form_data and form_data.n_days_ago else "selected" }}>Do not exclude any meals</option>
                        <option value="1" {{ "selected" if form_data and form_data.n_days_ago == "1" }}>1</option>
                        <option value="2" {{ "selected" if form_data and form_data.n_days_ago == "2" }}>2</option>
                        <option value="3" {{ "selected" if form_data and form_data.n_days_ago == "3" }}>3</option>
                    </select>
                </div>

                <div class="mb-3">
                    Creation parameters for menu (default nutrients values are taken from your profile):
                </div>

                <div id="nutrient_fields">
                    <div class="row mb-3">
                        <label for="min_calories" class="col-3 col-form-label">Calories min:</label>
                        <div class="col-9">
                            <input type="number" class="form-control" id="min_calories" name="min_calories" min="1" value="{{ form_data.min_calories if form_data and form_data.min_calories else current_user.min_calories }}" required>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label for="max_calories" class="col-3 col-form-label">Calories max:</label>
                        <div class="col-9">
                            <input type="number" class="form-control" id="max_calories" name="max_calories" min="1" value="{{ form_data.max_calories if form_data and form_data.max_calories else current_user.max_calories }}" required>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label for="min_proteins" class="col-3 col-form-label">Proteins min:</label>
                        <div class="col-9">
                            <input type="number" class="form-control" id="min_proteins" name="min_proteins" min="1" value="{{ form_data.min_proteins if form_data and form_data.min_proteins else current_user.min_proteins }}" required>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label for="max_proteins" class="col-3 col-form-label">Proteins max:</label>
                        <div class="col-9">
                            <input type="number" class="form-control" id="max_proteins" name="max_proteins" min="1" value="{{ form_data.max_proteins if form_data and form_data.max_proteins else current_user.max_proteins }}" required>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label for="min_fats" class="col-3 col-form-label">Fats min:</label>
                        <div class="col-9">
                            <input type="number" class="form-control" id="min_fats" name="min_fats" min="1" value="{{ form_data.min_fats if form_data and form_data.min_fats else current_user.min_fats }}" required>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label for="max_fats" class="col-3 col-form-label">Fats max:</label>
                        <div class="col-9">
                            <input type="number" class="form-control" id="max_fats" name="max_fats" min="1" value="{{ form_data.max_fats if form_data and form_data.max_fats else current_user.max_fats }}" required>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label for="min_carbohydrates" class="col-3 col-form-label">Carbohydrates min:</label>
                        <div class="col-9">
                            <input type="number" class="form-control" id="min_carbohydrates" name="min_carbohydrates" min="1" value="{{ form_data.min_carbohydrates if form_data and form_data.min_carbohydrates else current_user.min_carbohydrates }}" required>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label for="max_carbohydrates" class="col-3 col-form-label">Carbohydrates max:</label>
                        <div class="col-9">
                            <input type="number" class="form-control" id="max_carbohydrates" name="max_carbohydrates" min="1" value="{{ form_data.max_carbohydrates if form_data and form_data.max_carbohydrates else current_user.max_carbohydrates }}" required>
                        </div>
                    </div>
                </div>

                {% if errors %}
                    {% for field, error in errors.items() %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ error }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                {% endif %}

                <div class="text-center">
                    <button type="reset" class="btn btn-secondary btn-lg me-2">Reset</button>
                    <button type="submit" class="btn btn-primary btn-lg">Create</button>
                </div>
            </form>
        </div>
    </div>

    <script>
        document.getElementById('use_profile_nutrients').addEventListener('change', function() {
            let nutrientFields = document.getElementById('nutrient_fields');
            if (this.checked) {
                nutrientFields.style.display = 'none';
            } else {
                nutrientFields.style.display = 'block';
            }
        });
    </script>
{% endblock %}

src/templates/menu/history.html
{% extends 'base.html' %}

{% block head %}
    <title>History for {{ date }}</title>
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row justify-content-center mb-4">
            <div class="col-lg-8 col-md-12">
                <h1 class="mt-4 mb-4 text-center">History for {{ date }}</h1>

                <form method="get">
                    <div class="input-group">
                        <a class="btn btn-primary" href="{{ url_for('menu.history', date=prev_date) }}">Previous Day</a>
                        <input type="date" aria-label="Date" class="form-control" id="date" name="date" value="{{ date }}" required>
                        <button class="btn btn-secondary" type="submit">Go to Date</button>
                        <a class="btn btn-primary ml-3" href="{{ url_for('menu.history', date=next_date) }}" disabled>Next Day</a>
                    </div>
                </form>
            </div>
        </div>

        <div class="row mb-4">
            <div class="col">
                <h4>Total Nutrients</h4>
                <p>Total Price: {{ total_price }} €</p>
                <p>Total Calories: {{ total_calories }} kcal</p>
                <p>Total Proteins: {{ total_proteins }} g</p>
                <p>Total Fats: {{ total_fats }} g</p>
                <p>Total Carbohydrates: {{ total_carbohydrates }} g</p>
            </div>
        </div>


        {% for meal in meals %}
        <div class="row mb-4">
            <div class="col">
                <div class="card">
                    <div class="row g-0 d-flex align-items-center">
                        <div class="col-lg-3 col-md-5">
                            <img src="{{ meal.image }}" class="card-img-top" alt="Meal image">
                        </div>
                        <div class="col-lg-7 col-md-5">
                            <div class="card-body">
                                <h5 class="card-title">{{ meal.meal.name }}</h5>
                                <p class="card-text">
                                    Portion: {{ meal.portion }} g<br>
                                    Price: {{ meal.price }} €<br>
                                    Calories: {{ meal.calories }} kcal<br>
                                    Proteins: {{ meal.proteins }} g<br>
                                    Fats: {{ meal.fats }} g<br>
                                    Carbohydrates: {{ meal.carbohydrates }} g
                                </p>
                            </div>
                        </div>
                        <div class="col-lg-2 col-md-2 text-center mb-2 mb-md-0">
                            {% if meal.blacklisted %}
                                <a class="btn btn-danger me-md-2" href="{{ url_for('blacklist.remove', meal_id=meal.meal.id, return_page='history', history_date=date)}}" role="button">Remove from blacklist</a>
                            {% else %}
                                <a class="btn btn-success me-md-2" href="{{ url_for('blacklist.add', meal_id=meal.meal.id, history_date=date) }}" role="button">Add to blacklist</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
{% endblock %}